### ISSUE TITLE
Deprecated rules

### ISSUE THREAD

**Issue by eldario** [avto-dev/php-cs-fixer#14]
## Describe the bug

After executing the fix command, I see errors about outdated rules

### Expected behaviour

No errors.

### Actual behaviour

```sh
- Rule "compact_nullable_typehint" is deprecated. Use "compact_nullable_type_declaration" instead.
- Rule "function_typehint_space" is deprecated. Use "type_declaration_spaces" instead.
- Rule "native_function_type_declaration_casing" is deprecated. Use "native_type_declaration_casing" instead.
- Rule "single_blank_line_before_namespace" is deprecated. Use "blank_lines_before_namespace" instead.
```

## Additional context

Replace deprecated rules.

**Comment by gomzyakov** [comment]
@eldario @helloween141

Set the correct rules in https://github.com/avto-dev/php-cs-fixer/pull/17
