### ISSUE TITLE
Incorrectly fixed list of class contants, separated by comma.

### ISSUE THREAD

**Issue by shirokovnv** [avto-dev/php-cs-fixer#9]
### Description

After upgrading from php version 7.4.16 to 8.1.7 and upgrading package version from 1.0 to 1.3, the fixer incorrectly indents 
list of constants in classes.

### Expected behaviour

Correct indentation of constants.

### Actual behaviour

Indentation of constants starts incorrectly from the second line.

### Steps to reproduce the behavior:

- Define list of class constants with beautyful indentation.

```php
class Myclass {
    public const
        IOS     = 'ios',
        ANDROID     = 'android',
        HUAWEI      = 'huawei';
...
```

- Run fixer and see incorrect indentation:

```php
class Myclass {
    public const
        IOS     = 'ios',
    ANDROID     = 'android', // ???
    HUAWEI      = 'huawei'; // ???
```

## System information

 - PHP version(s): [`8.1.7`]
 - Package version(s): [`1.3.0`]
 - Version of pulled inner-dependency `friendsofphp/php-cs-fixer` is `3.9.5`

**Comment by eldario** [comment]
@shirokovnv 

Fixed with new rule `single_class_element_per_statement` in #10
